### PR TITLE
Apply tribute to received token estimation and show tribute on the frontend

### PR DESCRIPTION
**Pull request by PabloCGL**
Addressing Issue #4. Now applies the tribute% to the number shown as "tokens received" to the user. Also tells you the % applied depeding on if you're buying or selling, and gives an estimate of the minimum received accounting for slippage (hardcoded at 1% slippage for now).
NOTE: this only applies to the frontend, and not the buy process itself. Setting a "minimum received" on the contract call will be adressed separately when working on issue #10

If this PR is accepted, some minor UX points will have to be addressed in regards to number display formatting and layout. I'd open relevant issues.

### CODE REVIEW

**Comment by PabloCGL** [comment]
@sembrestels I wanted to tag you as reviewer but it seems I can't?

**Comment by PabloCGL** [comment]
Now also sends the minimum to the smart contracts.

**Comment by PabloCGL** [comment]
Just noticed after the demo that I forgot to push the last change 🤦‍♂️ Now it everything should be there

**Comment by GriffGreen** [comment]
Might be cleaner to merge this and then add a new one

**Pull request merged**
